### ISSUE TITLE
Customizable estate icon size

### ISSUE THREAD

**Issue by MattiasSp** [origo-map/lmsearch-plugin#42]
When using the new config option to set a custom text for the estate icon, we should also be able to configure the size of the rectangle to contain the custom text.

![image](https://user-images.githubusercontent.com/2445979/149937962-81c74609-7075-4752-9b78-16924f1cb3a8.png)

**Comment by MattiasSp** [comment]
PR incoming.

Also, I'll leave a tip here that may or may not be useful to put in some docs or the readme.

To add multiple lines of text in the icon, one can add each line as <tspan> elements, each with their own relative position on the y-axis (credits to [Sergiu Dumitriu at StackOverflow](https://stackoverflow.com/a/16701952/1461981)):

```
<text font-size="1em" font-family="Arial" fill="black">
    <tspan x="5" dy="1.2em">Fastighets-</tspan>
    <tspan x="5" dy="1.2em">rapport</tspan>
</text>
```

**Comment by johnnyblasta** [comment]
Cool, someone besides me using this function :)

**Comment by MattiasSp** [comment]
OK if I add a custom icon size and custom text with two lines to the example config in the readme?

![image](https://user-images.githubusercontent.com/2445979/149959612-2394c56e-9586-42c4-96b7-931c49862f49.png)

**Comment by johnnyblasta** [comment]
> OK if I add a custom icon size and custom text with two lines to the example config in the readme?
> 
> ![image](https://user-images.githubusercontent.com/2445979/149959612-2394c56e-9586-42c4-96b7-931c49862f49.png)

Yes, thats a good idea.

**Comment by MattiasSp** [comment]
Another tip from [e03050](https://stackoverflow.com/a/57567670/1461981) at StackOverflow about the text content is to use `foreignobject`, which allows HTML contents and can wrap lines automatically. Although it won't work in IE 11.

```
<foreignobject x="5" dy="1.2em" width="100" height="60">
    <body xmlns="http://www.w3.org/1999/xhtml">
        <div><b>Fastighets-rapport</b></div>
    </body>
</foreignobject>
```
