### ISSUE TITLE
Search inputfield appearance

### ISSUE THREAD

**Issue by Owemyr** [origo-map/lmsearch-plugin#67]
A minor issue, some of the latest changes makes search inputfield not filling up white space and icons looks a bit small compared to default search.

![image](https://user-images.githubusercontent.com/47249045/178731788-318f549a-5d6a-4391-81ee-822468b230d7.png)

**Comment by johnnyblasta** [comment]
Hm, fills up fine on my screen:
![image](https://user-images.githubusercontent.com/48793206/178752324-e2f0d50c-5e47-47b6-a278-4a8446bdce6f.png)
Perhaps the icon is smaller than default search, but I never used the "default" search so don't know :)

**Comment by Owemyr** [comment]
Then i must check my fork for css changes, spooky :)

Icon/label-size looks good with new PR #68

**Comment by johnnyblasta** [comment]
> Then i must check my fork for css changes, spooky :)
> 
> Icon/label-size looks good with new PR #68

Can be something on my css also, since I didn't test with a clean Origo master 😄

**Comment by Owemyr** [comment]
Checked with a clean build of origo and lmsearch-plugin, it looks good.
So that problem was on my end (changed font-size on input css a long time a go and forgot about it) :)

Though did saw some inconsistency with search result list appearaence.

**With searchLabelText "Sök:"**
![image](https://user-images.githubusercontent.com/47249045/178991279-6d64f414-1a62-49e8-b929-5e31b2d5a9bd.png)

**Without searchLabelText " "**
![image](https://user-images.githubusercontent.com/47249045/178991929-4be250bc-c5af-4a43-b059-6df6be53d44f.png)

**No hit dialog** 
![image](https://user-images.githubusercontent.com/47249045/178991387-d48797ca-90c4-4697-97f2-5e1af534a050.png)

Not a big deal and a mather of taste but prefer list to be center align, like this.
![image](https://user-images.githubusercontent.com/47249045/178993457-ed1d3ce2-19cd-427f-9000-1e64706d57f8.png)
